# Load Multiple Sheets from Excel

In [1]:
import pandas as pd

In [2]:
pd.read_excel('Sales_Data.xlsx')

    Order_ID   Product  Quantity   Price     Region
0       1000  Keyboard         2  106847  Islamabad
1       1001    Laptop         1   18813   Peshawar
2       1002  Keyboard        10   58200     Lahore
3       1003  Keyboard         7   88394    Karachi
4       1004     Mouse         4   84863    Karachi
..       ...       ...       ...     ...        ...
95      1095    Laptop         3   26510   Peshawar
96      1096    Laptop         5   45491  Islamabad
97      1097     Mouse         9  101038   Peshawar
98      1098     Mouse         7   35738     Lahore
99      1099     Mouse         4  115144     Quetta

[100 rows x 5 columns]

In [3]:
all_sheets = pd.read_excel('Sales_Data.xlsx', sheet_name=None)
all_sheets

{'January':     Order_ID   Product  Quantity   Price     Region
 0       1000  Keyboard         2  106847  Islamabad
 1       1001    Laptop         1   18813   Peshawar
 2       1002  Keyboard        10   58200     Lahore
 3       1003  Keyboard         7   88394    Karachi
 4       1004     Mouse         4   84863    Karachi
 ..       ...       ...       ...     ...        ...
 95      1095    Laptop         3   26510   Peshawar
 96      1096    Laptop         5   45491  Islamabad
 97      1097     Mouse         9  101038   Peshawar
 98      1098     Mouse         7   35738     Lahore
 99      1099     Mouse         4  115144     Quetta

 [100 rows x 5 columns],
 'February':     Order_ID   Product  Quantity   Price     Region
 0       1000   Printer         5   85170   Peshawar
 1       1001     Mouse         7   14382  Islamabad
 2       1002    Laptop         4  107642    Karachi
 3       1003  Keyboard         7   78964  Islamabad
 4       1004   Monitor         7   80694     Lahore
 ..       ...       ...       ...     ...        ...
 95      1095  Keyboard         8   36122     Lahore
 96      1096   Monitor         9   15834     Lahore
 97      1097     Mouse         9  115106   Peshawar
 98      1098  Keyboard         7   20772    Karachi
 99      1099  Keyboard        10   43974  Islamabad

 [100 rows x 5 columns],
 'March':     Order_ID   Product  Quantity   Price     Region
 0       1000  Keyboard         7   65568     Lahore
 1       1001     Mouse         4   55526     Quetta
 2       1002  Keyboard        10    8290    Karachi
 3       1003     Mouse         1   61740    Karachi
 4       1004  Keyboard         1   53282   Peshawar
 ..       ...       ...       ...     ...        ...
 95      1095   Monitor         2   11835     Quetta
 96      1096    Laptop         4   30103  Islamabad
 97      1097   Printer         2  107619     Quetta
 98      1098    Laptop        10   64776     Lahore
 99      1099   Printer         2   79183     Quetta

 [100 rows x 5 columns],
 'April':     Order_ID   Product  Quantity   Price    Region
 0       1000   Printer         2   56565  Peshawar
 1       1001  Keyboard         9   68795    Quetta
 2       1002   Monitor         9  107000   Karachi
 3       1003   Monitor         2   35744  Peshawar
 4       1004   Printer         5   79795    Quetta
 ..       ...       ...       ...     ...       ...
 95      1095     Mouse         7   98061    Quetta
 96      1096   Printer         6   41551    Quetta
 97      1097   Printer        10   22259    Quetta
 98      1098   Printer         9  101695   Karachi
 99      1099   Printer         4   71299    Lahore

 [100 rows x 5 columns],
 'May':     Order_ID  Product  Quantity  Price     Region
 0       1000   Laptop         9   2169     Lahore
 1       1001  Monitor         6  18135  Islamabad
 2       1002  Printer         4  93839   Peshawar
 3       1003  Monitor         2  78015   Peshawar
 4       1004    Mouse         6  93925     Quetta
 ..       ...      ...       ...    ...        ...
 95      1095  Printer         6  40046     Quetta
 96      1096  Monitor         1  80103     Quetta
 97      1097  Printer         2  43653     Quetta
 98      1098    Mouse         5  93964  Islamabad
 99      1099    Mouse         6  91835     Lahore

 [100 rows x 5 columns]}

In [4]:
all_sheets.keys()

dict_keys(['January', 'February', 'March', 'April', 'May'])

In [5]:
all_sheets.items()

dict_items([('January',     Order_ID   Product  Quantity   Price     Region
0       1000  Keyboard         2  106847  Islamabad
1       1001    Laptop         1   18813   Peshawar
2       1002  Keyboard        10   58200     Lahore
3       1003  Keyboard         7   88394    Karachi
4       1004     Mouse         4   84863    Karachi
..       ...       ...       ...     ...        ...
95      1095    Laptop         3   26510   Peshawar
96      1096    Laptop         5   45491  Islamabad
97      1097     Mouse         9  101038   Peshawar
98      1098     Mouse         7   35738     Lahore
99      1099     Mouse         4  115144     Quetta

[100 rows x 5 columns]), ('February',     Order_ID   Product  Quantity   Price     Region
0       1000   Printer         5   85170   Peshawar
1       1001     Mouse         7   14382  Islamabad
2       1002    Laptop         4  107642    Karachi
3       1003  Keyboard         7   78964  Islamabad
4       1004   Monitor         7   80694     Lahore
..       ...       ...       ...     ...        ...
95      1095  Keyboard         8   36122     Lahore
96      1096   Monitor         9   15834     Lahore
97      1097     Mouse         9  115106   Peshawar
98      1098  Keyboard         7   20772    Karachi
99      1099  Keyboard        10   43974  Islamabad

[100 rows x 5 columns]), ('March',     Order_ID   Product  Quantity   Price     Region
0       1000  Keyboard         7   65568     Lahore
1       1001     Mouse         4   55526     Quetta
2       1002  Keyboard        10    8290    Karachi
3       1003     Mouse         1   61740    Karachi
4       1004  Keyboard         1   53282   Peshawar
..       ...       ...       ...     ...        ...
95      1095   Monitor         2   11835     Quetta
96      1096    Laptop         4   30103  Islamabad
97      1097   Printer         2  107619     Quetta
98      1098    Laptop        10   64776     Lahore
99      1099   Printer         2   79183     Quetta

[100 rows x 5 columns]), ('April',     Order_ID   Product  Quantity   Price    Region
0       1000   Printer         2   56565  Peshawar
1       1001  Keyboard         9   68795    Quetta
2       1002   Monitor         9  107000   Karachi
3       1003   Monitor         2   35744  Peshawar
4       1004   Printer         5   79795    Quetta
..       ...       ...       ...     ...       ...
95      1095     Mouse         7   98061    Quetta
96      1096   Printer         6   41551    Quetta
97      1097   Printer        10   22259    Quetta
98      1098   Printer         9  101695   Karachi
99      1099   Printer         4   71299    Lahore

[100 rows x 5 columns]), ('May',     Order_ID  Product  Quantity  Price     Region
0       1000   Laptop         9   2169     Lahore
1       1001  Monitor         6  18135  Islamabad
2       1002  Printer         4  93839   Peshawar
3       1003  Monitor         2  78015   Peshawar
4       1004    Mouse         6  93925     Quetta
..       ...      ...       ...    ...        ...
95      1095  Printer         6  40046     Quetta
96      1096  Monitor         1  80103     Quetta
97      1097  Printer         2  43653     Quetta
98      1098    Mouse         5  93964  Islamabad
99      1099    Mouse         6  91835     Lahore

[100 rows x 5 columns])])

In [8]:
for name, df in all_sheets.items():
    print(name, df.shape)

January (100, 5)
February (100, 5)
March (100, 5)
April (100, 5)
May (100, 5)

In [9]:
combined_df = pd.concat([df.assign(Month=name) for name, df in all_sheets.items()], ignore_index=True)
combined_df

     Order_ID   Product  Quantity   Price     Region    Month
0        1000  Keyboard         2  106847  Islamabad  January
1        1001    Laptop         1   18813   Peshawar  January
2        1002  Keyboard        10   58200     Lahore  January
3        1003  Keyboard         7   88394    Karachi  January
4        1004     Mouse         4   84863    Karachi  January
..        ...       ...       ...     ...        ...      ...
495      1095   Printer         6   40046     Quetta      May
496      1096   Monitor         1   80103     Quetta      May
497      1097   Printer         2   43653     Quetta      May
498      1098     Mouse         5   93964  Islamabad      May
499      1099     Mouse         6   91835     Lahore      May

[500 rows x 6 columns]

In [10]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  500 non-null    int64
 1   Product   500 non-null    object
 2   Quantity  500 non-null    int64
 3   Price     500 non-null    int64
 4   Region    500 non-null    object
 5   Month     500 non-null    object
dtypes: int64(3), object(3)
memory usage: 23.6+ KB

In [11]:
combined_df['Total_Sales'] = combined_df['Quantity'] * combined_df['Price']
combined_df.head()

   Order_ID   Product  Quantity   Price     Region    Month  Total_Sales
0      1000  Keyboard         2  106847  Islamabad  January       213694
1      1001    Laptop         1   18813   Peshawar  January        18813
2      1002  Keyboard        10   58200     Lahore  January       582000
3      1003  Keyboard         7   88394    Karachi  January       618758
4      1004     Mouse         4   84863    Karachi  January       339452

In [12]:
combined_df.groupby('Month')['Total_Sales'].sum()

Month
April       39052480
February    31617688
January     34714432
March       28366110
May         31182576
Name: Total_Sales, dtype: int64

In [13]:
combined_df.to_csv('Combined_Sales_Data.csv', index=False)