In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Salaries.csv')
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

## ***1. Display Top 10  Rows of The Dataset***

In [4]:
df.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.0,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.0,51322.5,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

## ***2.Check Last 10 Rows of The Dataset***

In [5]:
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

## ***3. Find Shape our Dataset (Number of Rows and Number of Columns)***

In [6]:
df.shape

(148654, 13)

In [7]:
df.shape[1]

13

## ***4. Getting ALl Information About Our Dataset***

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

## ***5. Check Null Values In the Dataset***

In [9]:
df.isnull()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,False,False,False,False,False,False,True,False,False,False,True,False,True
1,False,False,False,False,False,False,True,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,False,False,True,False,True
3,False,False,False,False,False,False,True,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,False,False,False,False,False,False,False,False,False,False,True,False,False
148650,False,False,False,False,False,False,False,False,False,False,True,False,True
148651,False,False,False,False,False,False,False,False,False,False,True,False,True
148652,False,False,False,False,False,False,False,False,False,False,True,False,True
148653,False,False,False,False,False,False,False,False,False,False,True,False,False

In [10]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

## ***6. Drop ID, Notes, Agency and Status Columns***

In [11]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [12]:
df.drop(['Id','Notes','Agency','Status'])

KeyError: "['Id', 'Notes', 'Agency', 'Status'] not found in axis"

In [13]:
df = df.drop(['Id','Notes','Agency','Status'],axis=1)

In [14]:
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

## ***7. Get Overall Statistics About the Dataframe***

In [15]:
df.describe()

            TotalPay  TotalPayBenefits           Year
count  148654.000000     148654.000000  148654.000000
mean    74768.321972      93692.554811    2012.522643
std     50517.005274      62793.533483       1.117538
min      -618.130000       -618.130000    2011.000000
25%     36168.995000      44065.650000    2012.000000
50%     71426.610000      92404.090000    2013.000000
75%    105839.135000     132876.450000    2014.000000
max    567595.430000     567595.430000    2014.000000

In [16]:
df.describe(include='all')

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148049.0,148654.0,148654.0,112495.0,148654.000000,148654.000000,148654.000000
unique,110811,2159,109900.0,66555.0,84968.0,99635.0,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,0.0,0.0,0.0,0.0,NaN,NaN,NaN
freq,13,7036,875.0,66103.0,35218.0,1053.0,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,74768.321972,93692.554811,2012.522643
std,NaN,NaN,NaN,NaN,NaN,NaN,50517.005274,62793.533483,1.117538
min,NaN,NaN,NaN,NaN,NaN,NaN,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,105839.135000,132876.450000,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,567595.430000,567595.430000,2014.000000

## ***8. Find Occurrence of The Employee Names (Top 5)***

In [17]:
df.EmployeeName.value_counts()

EmployeeName
Kevin Lee                   13
Richard Lee                 11
Steven Lee                  11
William Wong                11
Stanley Lee                  9
                            ..
Jeffrey Skover               1
Ken Dever                    1
Kevin Whitfield              1
Granville McCollough III     1
Joe Lopez                    1
Name: count, Length: 110811, dtype: int64

In [18]:
df.EmployeeName.value_counts().head()

EmployeeName
Kevin Lee       13
Richard Lee     11
Steven Lee      11
William Wong    11
Stanley Lee      9
Name: count, dtype: int64

## ***9. Find The Number of Unique Job Titles***

In [19]:
df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], shape=(2159,), dtype=object)

In [16]:
# pd.options.display.max_rows = None

In [1]:
for i in df.JobTitle.unique():
    print(i)

NameError: name 'df' is not defined

In [20]:
df.JobTitle.nunique()

2159

## ***10. Total Number of Job Titles Contain Captain***

In [19]:
df[df.JobTitle.str.contains("CAPTAIN",case=False)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
11,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.0,87082.62,110804.3,NaN,297608.92,297608.92,2011,NaN,San Francisco,NaN
17,18,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011,NaN,San Francisco,NaN
22,23,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116604,116605,Gregory L Stewart,"Captain, Fire Suppression",73355.21,18517.18,49917.73,25608.77,141790.12,167398.89,2014,NaN,San Francisco,PT
120867,120868,Michael J Moran,Captain 3,7660.0,1496.09,126560.36,2189.51,135716.45,137905.96,2014,NaN,San Francisco,PT
122361,122362,Michael V Rolovich,"Captain, Fire Suppression",0.0,0.0,130320.75,0.0,130320.75,130320.75,2014,NaN,San Francisco,PT
126588,126589,Stephen M Tittel,Captain 3,68491.89,0.0,23721.91,19020.79,92213.80,111234.59,2014,NaN,San Francisco,PT
132232,132233,Jeanne M Seyler,"Captain, Fire Suppression",61039.43,2285.30,7548.29,20113.76,70873.02,90986.78,2014,NaN,San Francisco,PT

In [21]:
df[df.JobTitle.str.contains("CAPTAIN",case=False)].sum()

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [27]:
df.JobTitle.str.contains("CAPTAIN",case=False)

0         False
1          True
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [26]:
df.JobTitle.str.contains("CAPTAIN",case=False).sum()

np.int64(552)

## ***11. Display All The Employee Names From Fire Department***

In [24]:
df[df['JobTitle'].str.contains("FIRE DEPARTMENT", case=False)]['EmployeeName']

4              PATRICK GARDNER
6                    ALSON LEE
8               MICHAEL MORRIS
9           JOANNE HAYES-WHITE
10               ARTHUR KENNEY
                  ...
32623             JAMES BARDEN
36162       Joanne Hayes-White
72926     Joanne M Hayes-White
102303          Robert E Evans
110535    Joanne M Hayes-White
Name: EmployeeName, Length: 226, dtype: object

In [26]:
df[df.JobTitle.str.contains('Fire',case=False)]['EmployeeName']

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: object

## ***12. Find Minimum, Maximum, Average BasepPay***

In [28]:
df['BasePay'] = pd.to_numeric(df['BasePay'], errors='coerce')

# Calculate statistics
min_base_pay = df['BasePay'].min()
max_base_pay = df['BasePay'].max()
avg_base_pay = df['BasePay'].mean()

print(f"Minimum BasePay: {min_base_pay}")
print(f"Maximum BasePay: {max_base_pay}")
print(f"Average BasePay: {avg_base_pay:.2f}")

Minimum BasePay: -166.01
Maximum BasePay: 319275.01
Average BasePay: 66325.45

In [33]:
df.BasePay = df.BasePay.replace('Not Provided',0).astype(float)
df.BasePay

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...
148649         0.00
148650          NaN
148651          NaN
148652          NaN
148653         0.00
Name: BasePay, Length: 148654, dtype: float64

In [35]:
df.BasePay.min()

-166.01

In [36]:
df.BasePay.max()

319275.01

In [53]:
df.BasePay.mean()

np.float64(66325.44884048769)

In [57]:
df.EmployeeName = df.EmployeeName.replace('Not provided','NAN')
df.EmployeeName

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650                  NAN
148651                  NAN
148652                  NAN
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

In [45]:
df[df['EmployeeName'].str.contains('Not provided', case=False, na=False)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148646,148647,Not provided,Not provided,NaN,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,Not Provided,Not Provided,Not Provided,0.0,0.0,2014,NaN,San Francisco,NaN

## ***13. Find Job Title of ALBERT PARDINI***

In [48]:
df[df['EmployeeName']== 'ALBERT PARDINI']['JobTitle']

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

## ***14. How Much ALBERT PARDINI Make (Include TotalPayBenefits)?***

In [50]:
df[df['EmployeeName']== 'ALBERT PARDINI']['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

## ***15. Find Average BasePay Of All Employee Per Year***

In [58]:
df.Year.unique()

array([2011, 2012, 2013, 2014])

In [59]:
df.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [60]:
df.groupby('Year')['BasePay'].agg(['min', 'max', 'mean', 'count'])

         min        max          mean  count
Year
2011    0.00  294580.02  63595.956517  36159
2012 -166.01  302578.00  65436.406857  36766
2013   15.83  319275.01  69630.030216  37001
2014    0.00  318835.49  66564.421924  38119

## ***16. Find Average BasePay Of All Employee Per Job Title***

In [61]:
df.groupby('JobTitle')['BasePay'].mean()

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                     66374.400000
                                                      ...
X-RAY LABORATORY AIDE                             47664.773077
X-Ray Laboratory Aide                             46086.387100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
Youth Comm Advisor                                39077.957500
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 2159, dtype: float64

In [65]:
df[df['JobTitle']== 'ACCOUNTANT']['BasePay'].mean()

np.float64(46643.172)

## ***17. Find Top 5 Most Common Jobs***

In [66]:
top_5_jobs = df['JobTitle'].value_counts().head(5)
print(top_5_jobs)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [69]:
df.JobTitle.value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

### 18. Find the Employee with the Highest Total Pay

In [23]:
highest_paid = df.loc[df['TotalPay'].idxmax()]
print(highest_paid['EmployeeName'], highest_paid['TotalPay'])

NATHANIEL FORD 567595.43

In [24]:
df.loc[df['TotalPay'].idxmax()]

EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Name: 0, dtype: object

In [28]:
df.loc[df['TotalPay'].idxmax()]['EmployeeName']

'NATHANIEL FORD'

In [29]:
df.loc[df['TotalPay'].idxmax()]['TotalPay']

np.float64(567595.43)

## 19. Find the Employee with the Highest TotalPayBenefits

In [31]:
highest_benefits = df.loc[df['TotalPayBenefits'].idxmax()]
print(highest_benefits['EmployeeName'], highest_benefits['TotalPayBenefits'])

NATHANIEL FORD 567595.43

## 20. Find the Top 10 Highest Paid Employees

In [34]:
top_10_paid = df.nlargest(10, 'TotalPay')[['EmployeeName', 'JobTitle', 'TotalPay']]
print(top_10_paid)

                EmployeeName                                        JobTitle  \
0             NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1               GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)
110531           David Shinn                                  Deputy Chief 3
110532            Amy P Hart                               Asst Med Examiner
36159         Gary Altenberg                    Lieutenant, Fire Suppression
36167          John Goldberg                                       Captain 3
72927            Samson  Lai                  Battalion Chief, Fire Suppress
110536       Ellen G Moffatt                               Asst Med Examiner
110533  William J Coaker Jr.                        Chief Investment Officer
72925         Gregory P Suhr                                 Chief of Police

         TotalPay
0       567595.43
1       538909.28
110531  471952.64
110532  390111.98
36159   362844.66
36167   350403.41
72927   347102.32
110536  344187.46
110533  339653.70
72925   339282.07

## 21. Find the Employee with the Highest Overtime Pay

In [36]:
highest_overtime = df.loc[df['OvertimePay'].idxmax()]
print(highest_overtime['EmployeeName'], highest_overtime['OvertimePay'])

TypeError: '>' not supported between instances of 'str' and 'float'

In [37]:
##22. Find the Number of Employees per Year

In [38]:
employees_per_year = df['Year'].value_counts().sort_index()
print(employees_per_year)

Year
2011    36159
2012    36766
2013    37606
2014    38123
Name: count, dtype: int64

In [39]:
# 23. Find the Average Overtime Pay by Year

In [40]:
df['OvertimePay'] = pd.to_numeric(df['OvertimePay'], errors='coerce')
avg_overtime_per_year = df.groupby('Year')['OvertimePay'].mean()
print(avg_overtime_per_year)

Year
2011    4531.065429
2012    5023.417824
2013    5281.641980
2014    5401.993737
Name: OvertimePay, dtype: float64

In [41]:
# 24. Find the Total Payroll for Each Year

In [42]:
total_payroll_per_year = df.groupby('Year')['TotalPay'].sum()
print(total_payroll_per_year)

Year
2011    2.594195e+09
2012    2.724848e+09
2013    2.918656e+09
2014    2.876911e+09
Name: TotalPay, dtype: float64

In [43]:
# 25. Find the Most Common First Names

In [44]:
df['FirstName'] = df['EmployeeName'].str.split().str[0]
most_common_names = df['FirstName'].value_counts().head(10)
print(most_common_names)

FirstName
Michael    2070
John       1542
David      1444
James      1233
Robert     1206
Joseph      822
William     812
Maria       805
Richard     785
Daniel      770
Name: count, dtype: int64

In [45]:
# 26. Find Employees Who Earned $0 Total Pay

In [46]:
zero_pay_employees = df[df['TotalPay'] == 0]
print(f"Number of employees with $0 TotalPay: {len(zero_pay_employees)}")
print(zero_pay_employees[['EmployeeName', 'JobTitle', 'Year']].head(10))

Number of employees with $0 TotalPay: 368
             EmployeeName                                    JobTitle  Year
36156      PAULETTE ADAMS  STATIONARY ENGINEER, WATER TREATMENT PLANT  2011
36157       KAUKAB MOHSIN                            TRANSIT OPERATOR  2011
36158  JOSEPHINE MCCREARY                                  MANAGER IV  2011
70877       Roland Baylon                       Deputy Court Clerk II  2012
70927    Felecia Phillips                            Registered Nurse  2012
70928     Robert Giannini                                     Painter  2012
70932          Nelly Kuan                   Senior Eligibility Worker  2012
70933     William Mathews                   Transit Power Line Worker  2012
70942       Gayle Mathews                  Senior Collections Officer  2012
70956        Linda Carter                         Transit Car Cleaner  2012

In [47]:
# 27. Find the Average Total Pay by Job Title (Top 10)

In [48]:
avg_pay_by_job = df.groupby('JobTitle')['TotalPay'].mean().sort_values(ascending=False).head(10)
print(avg_pay_by_job)

JobTitle
GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY    399211.275000
Chief Investment Officer                          339653.700000
Chief of Police                                   329183.646667
Chief, Fire Department                            325971.683333
DEPUTY DIRECTOR OF INVESTMENTS                    307899.460000
CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)            302377.730000
Gen Mgr, Public Trnsp Dept                        297769.413333
Asst Chf of Dept (Fire Dept)                      281763.483889
DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      279359.560000
Dep Dir for Investments, Ret                      278592.545000
Name: TotalPay, dtype: float64

In [49]:
# 28. Find the Year with the Highest Average Pay

In [50]:
highest_avg_pay_year = df.groupby('Year')['TotalPay'].mean().idxmax()
highest_avg_pay_value = df.groupby('Year')['TotalPay'].mean().max()
print(f"Year with highest average pay: {highest_avg_pay_year} - ${highest_avg_pay_value:.2f}")

Year with highest average pay: 2013 - $77611.44

In [51]:
# 29. Count Employees by Status

In [52]:
status_counts = df['Status'].value_counts(dropna=False)
print(status_counts)

KeyError: 'Status'

In [53]:
# 30. Calculate the Correlation Between BasePay and TotalPay

In [54]:
correlation = df['BasePay'].corr(df['TotalPay'])
print(f"Correlation between BasePay and TotalPay: {correlation:.4f}")

ValueError: could not convert string to float: 'Not Provided'